services:
  db:
    image: mariadb:12.2.2
    container_name: wrwwp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wpuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wppassword}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wrwwp-wordpress
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/voxel07/wrwwp:latest
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      DB_HOST: ${DB_HOST:-wrwwp-db}
      DB_NAME: ${DB_NAME:-wordpress}
      DB_USER: ${DB_USER:-wpuser}
      DB_PASSWORD: ${DB_PASSWORD:-wppassword}
      WP_ENV: ${WP_ENV:-development}
      WP_HOME: ${WP_HOME:-http://localhost:8080}
      WP_SITEURL: ${WP_SITEURL:-http://localhost:8080/wp}
      AUTH_KEY: ${AUTH_KEY:-generateme}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY:-generateme}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY:-generateme}
      NONCE_KEY: ${NONCE_KEY:-generateme}
      AUTH_SALT: ${AUTH_SALT:-generateme}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT:-generateme}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT:-generateme}
      NONCE_SALT: ${NONCE_SALT:-generateme}
      WP_OPTION_IMMICH_PROXY_URL: ${WP_OPTION_IMMICH_PROXY_URL:-}
      WP_OPTION_IMMICH_DROP_URL: ${WP_OPTION_IMMICH_DROP_URL:-}
      WP_OPTION_IMMICH_KIOSK_URL: ${WP_OPTION_IMMICH_KIOSK_URL:-}
      WP_PLUGINS_ACTIVATE: ${WP_PLUGINS_ACTIVATE:-all}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:-}
      OIDC_CLIENT_SCOPE: ${OIDC_CLIENT_SCOPE:-openid email profile}
      OIDC_ENDPOINT_LOGIN_URL: ${OIDC_ENDPOINT_LOGIN_URL:-}
      OIDC_ENDPOINT_USERINFO_URL: ${OIDC_ENDPOINT_USERINFO_URL:-}
      OIDC_ENDPOINT_TOKEN_URL: ${OIDC_ENDPOINT_TOKEN_URL:-}
      OIDC_ENDPOINT_END_SESSION_URL: ${OIDC_ENDPOINT_END_SESSION_URL:-}
      OIDC_JWKS_URI: ${OIDC_JWKS_URI:-}
      OIDC_ISSUER: ${OIDC_ISSUER:-}
    volumes:
      - wp_uploads:/var/www/html/web/app/uploads
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  wp_uploads:
