<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file lives one directory above the WordPress root (web/) for security.
 * WordPress is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
