<?php
/**
 * Theme functions and definitions.
 *
 * @package wrw
 */

/**
 * Enqueue scripts and styles.
 */
function airsoft_theme_enqueue_styles() {
	// Basic structural styles (resets handled by MUI CssBaseline, so we only need to enqueue our custom compiled style if it exists).
	wp_enqueue_style( 'airsoft-style', get_stylesheet_uri(), array(), wp_get_theme()->get( 'Version' ) );
	wp_enqueue_style( 'wrw-fonts', 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap', array(), wp_get_theme()->get( 'Version' ) );

	// Unenqueue vanilla-tilt as it's not needed with React/MUI.
	// React / Vite Bundle.
	$dist_url  = get_template_directory_uri() . '/dist';
	$dist_path = get_template_directory() . '/dist';

	// We configured Vite to output strictly to assets/main.js and potentially assets/vendor.js.
	if ( file_exists( $dist_path . '/assets/vendor.js' ) ) {
		wp_enqueue_script( 'wrw-react-vendor', $dist_url . '/assets/vendor.js', array(), wp_get_theme()->get( 'Version' ), true );
	}

	if ( file_exists( $dist_path . '/assets/main.js' ) ) {
		wp_enqueue_script( 'wrw-react-app', $dist_url . '/assets/main.js', array( 'wrw-react-vendor' ), wp_get_theme()->get( 'Version' ), true );
		// If there's a CSS file generated by Vite.
		if ( file_exists( $dist_path . '/assets/main.css' ) ) {
			wp_enqueue_style( 'wrw-react-style', $dist_url . '/assets/main.css', array(), wp_get_theme()->get( 'Version' ) );
		}
	}
}
add_action( 'wp_enqueue_scripts', 'airsoft_theme_enqueue_styles' );

// Allow modules for scripts enqueued by Vite.
add_filter(
	'script_loader_tag',
	function ( $tag, $handle, $src ) {
		if ( in_array( $handle, array( 'wrw-react-app', 'wrw-react-vendor' ), true ) ) {
			// phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedScript
			return '<script type="module" src="' . esc_url( $src ) . '"></script>';
		}
		return $tag;
	},
	10,
	3
);

require_once get_template_directory() . '/includes/user-profiles.php';
require_once get_template_directory() . '/includes/events.php';
require_once get_template_directory() . '/includes/announcements.php';
require_once get_template_directory() . '/includes/frontend-profile.php';
require_once get_template_directory() . '/includes/security-hardening.php';

/**
 * Theme setup.
 */
function airsoft_theme_setup() {
	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	register_nav_menus(
		array(
			'primary' => __( 'Primary Menu', 'airsoft-theme' ),
		)
	);
}
add_action( 'after_setup_theme', 'airsoft_theme_setup' );

// Auto-create pages and flush rewrites on theme activation (or init).
/**
 * Setup pages.
 */
function wrw_setup_pages() {
	if ( get_option( 'wrw_pages_created' ) !== 'rewrite7' ) {
		$pages = array(
			'team'           => array(
				'title'    => 'Team',
				'template' => 'page-team.php',
			),
			'regeln'         => array(
				'title'    => 'Regeln',
				'template' => 'page-regeln.php',
			),
			'sponsoren'      => array(
				'title'    => 'Sponsoren',
				'template' => 'page-sponsoren.php',
			),
			'galerie'        => array(
				'title'    => 'Galerie',
				'template' => 'page-galerie.php',
			),
			'events'         => array(
				'title'    => 'Events',
				'template' => 'page-events.php',
			),
			'announcements'  => array(
				'title'    => 'Announcements',
				'template' => 'page-announcements.php',
			),
			'profil'         => array(
				'title'    => 'Profil',
				'template' => 'page-profile.php',
			),
			'admin-overview' => array(
				'title'    => 'Admin Overview',
				'template' => 'page-admin-overview.php',
			),
			'community'      => array(
				'title'    => 'Forum',
				'template' => 'page-community.php',
			),
		);

		foreach ( $pages as $slug => $data ) {
			$page_check = get_page_by_path( $slug );
			if ( ! isset( $page_check->ID ) ) {
				$new_page_id = wp_insert_post(
					array(
						'post_title'  => $data['title'],
						'post_name'   => $slug,
						'post_status' => 'publish',
						'post_type'   => 'page',
					)
				);
				if ( $new_page_id && ! is_wp_error( $new_page_id ) ) {
					update_post_meta( $new_page_id, '_wp_page_template', $data['template'] );
				}
			} else {
				update_post_meta( $page_check->ID, '_wp_page_template', $data['template'] );
			}
		}

		// Also set a static front page if not set.
		$home_check = get_page_by_path( 'home' );
		if ( ! isset( $home_check->ID ) ) {
			$home_id = wp_insert_post(
				array(
					'post_title'  => 'Home',
					'post_name'   => 'home',
					'post_status' => 'publish',
					'post_type'   => 'page',
				)
			);
			if ( $home_id && ! is_wp_error( $home_id ) ) {
				update_post_meta( $home_id, '_wp_page_template', 'front-page.php' );
				update_option( 'show_on_front', 'page' );
				update_option( 'page_on_front', $home_id );
			}
		}

		// Set permalink structure to post name.
		update_option( 'permalink_structure', '/%postname%/' );

		// Flush rewrite rules to avoid 404.
		flush_rewrite_rules();

		// Auto-activate all securely pulled composer plugins once.
		if ( ! function_exists( 'activate_plugin' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}
		$plugins = get_plugins();
		foreach ( $plugins as $plugin_path => $plugin_info ) {
			if ( ! is_plugin_active( $plugin_path ) ) {
				activate_plugin( $plugin_path );
			}
		}

		// Register Native WP Roles for Team Mapping.
		if ( ! get_role( 'vorstand' ) ) {
			add_role( 'vorstand', 'Vorstand', array( 'read' => true ) );
		}
		if ( ! get_role( 'mitglied' ) ) {
			add_role( 'mitglied', 'Mitglied', array( 'read' => true ) );
		}
		if ( ! get_role( 'frischling' ) ) {
			add_role( 'frischling', 'Frischling', array( 'read' => true ) );
		}

		update_option( 'wrw_pages_created', 'rewrite7' ); // Burst the check to force page generation.
	}
}
add_action( 'init', 'wrw_setup_pages' );
